# Generated by Django 3.0.5 on 2020-04-20 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjEffect',
            fields=[
                ('effictid', models.IntegerField(db_column='EffictID', primary_key=True, serialize=False)),
                ('cd', models.CharField(db_column='CD', max_length=255)),
                ('description', models.CharField(db_column='Description', max_length=255)),
            ],
            options={
                'db_table': 'proj_Effect',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjHero',
            fields=[
                ('heroid', models.IntegerField(db_column='HeroID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('type', models.CharField(db_column='Type', max_length=255)),
                ('attr_health', models.IntegerField(db_column='Attr_Health')),
                ('attr_damage', models.IntegerField(db_column='Attr_Damage')),
                ('attr_mana', models.IntegerField(db_column='Attr_Mana')),
                ('imageurl', models.CharField(blank=True, db_column='ImageUrl', max_length=255, null=True)),
                ('bio', models.CharField(blank=True, db_column='Bio', max_length=255, null=True)),
            ],
            options={
                'db_table': 'proj_Hero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjHeroLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_id', models.IntegerField()),
                ('attr_health', models.CharField(blank=True, db_column='Attr_Health', max_length=255, null=True)),
                ('attr_damage', models.CharField(blank=True, db_column='Attr_Damage', max_length=255, null=True)),
                ('attr_maga', models.CharField(blank=True, db_column='Attr_Maga', max_length=255, null=True)),
            ],
            options={
                'db_table': 'proj_hero_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjHeroTalent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heroid', models.IntegerField(db_column='HeroID')),
                ('talentid', models.IntegerField(db_column='TalentID')),
                ('level', models.IntegerField(db_column='Level')),
            ],
            options={
                'db_table': 'proj_Hero_Talent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjItem',
            fields=[
                ('itemid', models.IntegerField(db_column='ItemID', primary_key=True, serialize=False)),
                ('itemname', models.CharField(db_column='ItemName', max_length=255)),
                ('category', models.CharField(db_column='Category', max_length=255)),
                ('bonus', models.CharField(db_column='Bonus', max_length=255)),
                ('cost', models.CharField(db_column='Cost', max_length=255)),
                ('description', models.CharField(db_column='Description', max_length=255)),
                ('shop', models.CharField(db_column='Shop', max_length=255)),
            ],
            options={
                'db_table': 'proj_Item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjSkill',
            fields=[
                ('skillid', models.IntegerField(db_column='SkillID', primary_key=True, serialize=False)),
                ('skillname', models.CharField(db_column='SkillName', max_length=255)),
                ('imageurl', models.CharField(blank=True, db_column='ImageUrl', max_length=255, null=True)),
                ('description', models.CharField(db_column='Description', max_length=1024)),
            ],
            options={
                'db_table': 'proj_Skill',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjTalent',
            fields=[
                ('talentid', models.IntegerField(db_column='TalentID', primary_key=True, serialize=False)),
                ('talentname', models.CharField(db_column='TalentName', max_length=255)),
                ('description', models.CharField(db_column='Description', max_length=255)),
            ],
            options={
                'db_table': 'proj_Talent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjActiveeffect',
            fields=[
                ('effectid', models.OneToOneField(db_column='EffectID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dotabase.ProjEffect')),
                ('type', models.CharField(db_column='Type', max_length=255)),
                ('mana', models.CharField(db_column='Mana', max_length=255)),
            ],
            options={
                'db_table': 'proj_ActiveEffect',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjHerobadagainst',
            fields=[
                ('heroid_1', models.OneToOneField(db_column='HeroID_1', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dotabase.ProjHero')),
            ],
            options={
                'db_table': 'proj_HeroBadAgainst',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjHerobestcombos',
            fields=[
                ('heroid_1', models.OneToOneField(db_column='HeroID_1', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dotabase.ProjHero')),
            ],
            options={
                'db_table': 'proj_HeroBestCombos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjHerogoodagainst',
            fields=[
                ('heroid_1', models.OneToOneField(db_column='HeroID_1', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dotabase.ProjHero')),
            ],
            options={
                'db_table': 'proj_HeroGoodAgainst',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjHeroSkill',
            fields=[
                ('heroid', models.OneToOneField(db_column='HeroID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dotabase.ProjHero')),
            ],
            options={
                'db_table': 'proj_Hero_Skill',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjItemEffect',
            fields=[
                ('itemid', models.OneToOneField(db_column='ItemID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dotabase.ProjItem')),
            ],
            options={
                'db_table': 'proj_Item_Effect',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjItemRecipe',
            fields=[
                ('itemid_1', models.OneToOneField(db_column='ItemID_1', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dotabase.ProjItem')),
            ],
            options={
                'db_table': 'proj_Item_Recipe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjItemRecommend',
            fields=[
                ('heroid', models.OneToOneField(db_column='HeroID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dotabase.ProjHero')),
            ],
            options={
                'db_table': 'proj_Item_Recommend',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjPassiveeffect',
            fields=[
                ('peffectid', models.OneToOneField(db_column='PEffectID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dotabase.ProjEffect')),
                ('type', models.CharField(db_column='Type', max_length=255)),
                ('mana', models.CharField(db_column='Mana', max_length=255)),
            ],
            options={
                'db_table': 'proj_PassiveEffect',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjSkillEffect',
            fields=[
                ('skillid', models.OneToOneField(db_column='SkillID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dotabase.ProjSkill')),
            ],
            options={
                'db_table': 'proj_Skill_Effect',
                'managed': False,
            },
        ),
    ]
