# Generated by Django 3.0.5 on 2020-04-19 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dotabase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('hero_id', models.AutoField(primary_key=True, serialize=False)),
                ('bio', models.TextField()),
                ('name', models.TextField()),
                ('type', models.SmallIntegerField(choices=[(0, 'STRENGTH'), (1, 'AGILITY'), (2, 'INTELLIGENCE')])),
                ('health', models.IntegerField()),
                ('damage', models.IntegerField()),
                ('mana', models.IntegerField()),
                ('image_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HeroGoodAgainst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_against_target_hero', to='dotabase.Hero')),
                ('hero_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_against_hero', to='dotabase.Hero')),
            ],
        ),
        migrations.CreateModel(
            name='HeroBestCombos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_combos_target_hero', to='dotabase.Hero')),
                ('hero_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_combos_hero', to='dotabase.Hero')),
            ],
        ),
        migrations.CreateModel(
            name='HeroBadAgainst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bad_against_target_hero', to='dotabase.Hero')),
                ('hero_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bad_against_hero', to='dotabase.Hero')),
            ],
        ),
    ]
