# Generated by Django 3.0.5 on 2020-04-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotabase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authuser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'AuthUser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CorsheadersCorsmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cors', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'corsheaders_corsmodel',
                'managed': False,
            },
        ),
    ]
