# Generated by Django 3.0.5 on 2020-04-19 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dotabase', '0002_hero_herobadagainst_herobestcombos_herogoodagainst'),
    ]

    operations = [
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('effect_id', models.AutoField(primary_key=True, serialize=False)),
                ('cd', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HeroLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hero_id', models.IntegerField()),
                ('health', models.IntegerField()),
                ('damage', models.IntegerField()),
                ('mana', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('category', models.TextField()),
                ('bonus', models.TextField()),
                ('cost', models.TextField()),
                ('description', models.TextField()),
                ('shop', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('image_url', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='herobadagainst',
            unique_together={('hero_1', 'hero_2')},
        ),
        migrations.AlterUniqueTogether(
            name='herobestcombos',
            unique_together={('hero_1', 'hero_2')},
        ),
        migrations.AlterUniqueTogether(
            name='herogoodagainst',
            unique_together={('hero_1', 'hero_2')},
        ),
        migrations.CreateModel(
            name='PassiveEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('mana', models.IntegerField()),
                ('effect_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passive_effect', to='dotabase.Effect')),
            ],
        ),
        migrations.CreateModel(
            name='ItemEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_effect_effect', to='dotabase.Effect')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_effect_item', to='dotabase.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('mana', models.IntegerField()),
                ('effect_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_effect', to='dotabase.Effect')),
            ],
        ),
        migrations.CreateModel(
            name='SkillEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_effect_effect', to='dotabase.Effect')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_effect_skill', to='dotabase.Skill')),
            ],
            options={
                'unique_together': {('skill_id', 'effect_id')},
            },
        ),
        migrations.CreateModel(
            name='ItemRecommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_recommend_hero', to='dotabase.Hero')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_recommend_item', to='dotabase.Item')),
            ],
            options={
                'unique_together': {('hero_id', 'item_id')},
            },
        ),
        migrations.CreateModel(
            name='ItemRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_recipe_1', to='dotabase.Item')),
                ('item_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_recipe_2', to='dotabase.Item')),
            ],
            options={
                'unique_together': {('item_1', 'item_2')},
            },
        ),
        migrations.CreateModel(
            name='HeroTalent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
                ('hero_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_talent_hero', to='dotabase.Hero')),
                ('talent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_talent_talent', to='dotabase.Talent')),
            ],
            options={
                'unique_together': {('hero_id', 'talent_id')},
            },
        ),
        migrations.CreateModel(
            name='HeroSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_skill_hero', to='dotabase.Hero')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_skill_skill', to='dotabase.Skill')),
            ],
            options={
                'unique_together': {('hero_id', 'skill_id')},
            },
        ),
    ]
